---
title: "Weight of Fish"
author: "Anthony Benitez"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

# Predicting Fish Weight


## Perch

```{r}
Fish <- read.csv("Fish.csv")
perch <- filter(Fish, Species == "Perch")
```

```{r}
perch <- select(perch,-Species)
```

### Best Models


### Best Two regressor model
```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="topright",main="Adjusted R^2")
```
The best two regressor model is height and weight because those are the highest adjusted r squared.

```{r}
perchmodel <- lm(Weight ~ Height + Width, data = perch)
summary.lm(perchmodel)
```

```{r}
pmodel <- lm(Weight ~ Height + Width + Length1 + Length2 + Length3, data = perch)
summary.lm(pmodel)
```

## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements